---
- include_tasks: build_flat.yml
  with_items: "{{ VAR_RH_xinetd }}"
  loop_control:
    loop_var: parameter
  when: VAR_RH_xinetd is defined

- name: Restart xinetd.
  systemd:
    state: restarted
    name: xinetd
  when: VAR_xinetd_reboot
