---
- name: Write file.({{ parameter.path }})
  lineinfile:
    path: "{{ parameter.path }}"
    regexp: '^\s*{{ item.key }}=.*'
    line: '{{ item.key }}={{ item.value }}'
  with_dict:
    "{{ parameter.properties }}"
  register: lineinfile_result

- name: Restart vsftpd.
  systemd:
    state: restarted
    name: vsftpd
  when: lineinfile_result.changed
